
-- EMPLOYEE table: base table for all employees
CREATE TABLE EMPLOYEE (
    EMPLOYEE_ID INT PRIMARY KEY,
    SSN CHAR(11) UNIQUE,
    Name VARCHAR(100),
    Address VARCHAR(200),
    Phone VARCHAR(15)
);

-- SALES_REP table: subtype of EMPLOYEE
CREATE TABLE SALES_REP (
    EMPLOYEE_ID INT PRIMARY KEY,
    Salary DECIMAL(10,2),
    Commission DECIMAL(10,2),
    FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEE(EMPLOYEE_ID)
);

-- DRIVER table: subtype of EMPLOYEE
CREATE TABLE DRIVER (
    EMPLOYEE_ID INT PRIMARY KEY,
    DriverLicenseNo VARCHAR(50),
    LicenseExpDate DATE,
    FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEE(EMPLOYEE_ID)
);

-- CUSTOMER table
CREATE TABLE CUSTOMER (
    CUSTOMER_ID INT PRIMARY KEY,
    CompanyName VARCHAR(100),
    BillingAddress VARCHAR(200),
    ContactPersonName VARCHAR(100),
    ContactPhone VARCHAR(15)
);

-- ITEM table
CREATE TABLE ITEM (
    ITEM_ID INT PRIMARY KEY,
    ItemName VARCHAR(100),
    UnitPrice DECIMAL(10,2),
    UnitsInStock INT
);

-- TRUCK table
CREATE TABLE TRUCK (
    TRUCK_ID INT PRIMARY KEY,
    VehicleNo VARCHAR(50),
    LicensePlate VARCHAR(20),
    LicenseExpDate DATE,
    InspectionExpDate DATE,
    DRIVER_ID INT UNIQUE,
    FOREIGN KEY (DRIVER_ID) REFERENCES DRIVER(EMPLOYEE_ID)
);

-- ORDERS table
CREATE TABLE ORDERS (
    ORDER_ID INT PRIMARY KEY,
    OrderDate DATE,
    DeliveryAddress VARCHAR(200),
    CUSTOMER_ID INT,
    SALESREP_ID INT,
    TRUCK_ID INT,
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID),
    FOREIGN KEY (SALESREP_ID) REFERENCES SALES_REP(EMPLOYEE_ID),
    FOREIGN KEY (TRUCK_ID) REFERENCES TRUCK(TRUCK_ID)
);

-- ORDER_ITEM table: bridge between ORDERS and ITEM
CREATE TABLE ORDER_ITEM (
    ORDER_ID INT,
    ITEM_ID INT,
    Quantity INT,
    ExtendedPrice DECIMAL(10,2),
    PRIMARY KEY (ORDER_ID, ITEM_ID),
    FOREIGN KEY (ORDER_ID) REFERENCES ORDERS(ORDER_ID),
    FOREIGN KEY (ITEM_ID) REFERENCES ITEM(ITEM_ID)
);
